[project]
name = "droid-application"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "gpiozero>=2.0.1",
    "nicegui>=3.3.1",
]

[tool.uv]
exclude-dependencies = ["uvloop"]
